[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
password-checker-methods = { path = "../methods" }
password-checker-shared = { path = "../shared" }
risc0-zkvm = { version = "0.16.1" }
serde = "1.0"